import type { Command, Option } from 'commander';

/**
 * Shell completion scripts for the CodeFarmer CLI. Generated from the live
 * Commander command tree by `codefarmer completions <bash|zsh|fish>` so the
 * scripts never drift from the actual commands and options.
 */

interface CompletionCommand {
  /** Full command path, for example "sessions export". */
  path: string;
  description: string;
  /** Long or short option flags (for example "--session"), globals included. */
  options: string[];
}

function optionFlags(command: Command): string[] {
  const flags = new Set<string>();
  for (const option of command.options) {
    const flag = option.long ?? option.short;
    if (flag !== undefined) flags.add(flag);
  }
  return [...flags];
}

function rootOptions(program: Command): string[] {
  const flags = new Set([...optionFlags(program), '--help', '--version']);
  return [...flags];
}

function collectCommands(program: Command): CompletionCommand[] {
  const globalOptions = rootOptions(program);
  const commands: CompletionCommand[] = [];
  const visit = (command: Command, parents: string[]): void => {
    for (const child of command.commands) {
      const path = [...parents, child.name()].join(' ');
      const options = [...new Set([...globalOptions, ...optionFlags(child)])];
      commands.push({ path, description: child.description(), options });
      visit(child, [...parents, child.name()]);
    }
  };
  visit(program, []);
  return commands;
}

/** Single-quote a value for bash, zsh, and fish scripts. */
function shellQuote(value: string): string {
  return `'${value.replaceAll("'", "'\\''")}'`;
}

function optionsFunction(
  commands: CompletionCommand[],
  globalOptions: string[],
): string {
  const cases = [
    `      '') echo ${shellQuote(globalOptions.join(' '))} ;;`,
    ...commands.map(
      (command) =>
        `      ${shellQuote(command.path)}) echo ${shellQuote(command.options.join(' '))} ;;`,
    ),
    `      *) echo ${shellQuote(globalOptions.join(' '))} ;;`,
  ];
  return `  case "$1" in
${cases.join('\n')}
  esac`;
}

function bashScript(program: Command, programName: string): string {
  const commands = collectCommands(program);
  const globalOptions = rootOptions(program);
  const allList = commands.map((command) => shellQuote(command.path)).join(' ');
  return `# bash completion for ${programName}
# Generated by \`${programName} completions bash\`; source it from ~/.bashrc:
#   source <(${programName} completions bash)

_${programName}_options() {
${optionsFunction(commands, globalOptions)}
}

_${programName}() {
  local cur="\${COMP_WORDS[COMP_CWORD]}"
  local -a all
  all=(${allList})
  local path=""
  local i word candidate
  for ((i = 1; i < COMP_CWORD; i++)); do
    word="\${COMP_WORDS[i]}"
    case "$word" in
      -*) continue ;;
    esac
    local nextPath="\${path}\${word}"
    local found=0
    for candidate in "\${all[@]}"; do
      if [[ "$candidate" == "$nextPath" || "$candidate" == "$nextPath "* ]]; then
        found=1
        break
      fi
    done
    if ((found)); then path="\${nextPath} "; fi
  done
  path="\${path% }"

  if [[ "$cur" == -* ]]; then
    COMPREPLY=($(compgen -W "$(_${programName}_options "$path")" -- "$cur"))
    return
  fi

  local -a matches
  for candidate in "\${all[@]}"; do
    if [[ -z "$path" ]]; then
      if [[ "$candidate" != *" "* ]]; then matches+=("$candidate"); fi
    elif [[ "$candidate" == "$path "* ]]; then
      matches+=("\${candidate#"$path "}")
    fi
  done
  if [[ "$path" == "completions" && \${#matches[@]} -eq 0 ]]; then
    matches=('bash' 'zsh' 'fish')
  fi
  COMPREPLY=($(compgen -W "\${matches[*]}" -- "$cur"))
}
complete -F _${programName} ${programName}
`;
}

function zshScript(program: Command, programName: string): string {
  const commands = collectCommands(program);
  const globalOptions = rootOptions(program);
  const allList = commands.map((command) => shellQuote(command.path)).join(' ');
  const descList = commands
    .map((command) => shellQuote(`${command.path}:${command.description}`))
    .join(' ');
  return `#compdef ${programName}
# Generated by \`${programName} completions zsh\`; source it from ~/.zshrc:
#   source <(${programName} completions zsh)

_${programName}_options() {
${optionsFunction(commands, globalOptions)}
}

_${programName}() {
  local -a all descs matches
  all=(${allList})
  descs=(${descList})
  local path="" i word candidate nextPath
  for ((i = 2; i < CURRENT; i++)); do
    word="\${words[i]}"
    case "$word" in
      -*) continue ;;
    esac
    nextPath="\${path}\${word}"
    local found=0
    for candidate in "\${all[@]}"; do
      if [[ "$candidate" == "$nextPath" || "$candidate" == "$nextPath "* ]]; then
        found=1
        break
      fi
    done
    if ((found)); then path="\${nextPath} "; fi
  done
  path="\${path% }"

  if [[ "\${words[CURRENT]}" == -* ]]; then
    matches=(\${(s: :)$(_${programName}_options "$path")})
    _describe 'option' matches
    return
  fi

  local idx
  for ((idx = 1; idx <= \${#all[@]}; idx++)); do
    candidate="\${all[idx]}"
    if [[ -z "$path" ]]; then
      if [[ "$candidate" != *" "* ]]; then matches+=("\${descs[idx]}"); fi
    elif [[ "$candidate" == "$path "* ]]; then
      matches+=("\${descs[idx]#"$path "}")
    fi
  done
  if [[ "$path" == "completions" && \${#matches[@]} -eq 0 ]]; then
    matches=('bash' 'zsh' 'fish')
  fi
  if (( \${#matches[@]} )); then
    _describe 'command' matches
  else
    _files
  fi
}
compdef _${programName} ${programName}
`;
}

function fishScript(program: Command, programName: string): string {
  const commands = collectCommands(program);
  const globalOptions = rootOptions(program);
  const lines = [
    `# fish completion for ${programName}`,
    `# Generated by \`${programName} completions fish\`; save it as`,
    `# ~/.config/fish/completions/${programName}.fish`,
    '',
  ];
  for (const command of commands) {
    const segments = command.path.split(' ');
    const name = segments.at(-1) ?? '';
    const parent = segments.slice(0, -1);
    const condition =
      parent.length === 0
        ? '__fish_use_subcommand'
        : `__fish_seen_subcommand_from ${parent.join(' ')}`;
    lines.push(
      `complete -c ${programName} -n '${condition}' -a ${shellQuote(name)} -d ${shellQuote(command.description)}`,
    );
  }
  lines.push(
    `complete -c ${programName} -n '__fish_seen_subcommand_from completions' -a 'bash zsh fish' -d '补全脚本类型：bash、zsh 或 fish'`,
  );

  const optionLines: string[] = [];
  for (const flag of [...globalOptions, ...commands.flatMap((command) => command.options)]) {
    const option = findOption(program, flag);
    if (option === undefined) continue;
    const flags: string[] = [];
    if (option.short !== undefined) flags.push(`-s ${option.short.replace(/^-/, '')}`);
    if (option.long !== undefined) flags.push(`-l ${option.long.replace(/^--/, '')}`);
    if (option.required || option.optional) flags.push('-r');
    const description = option.description.length > 0 ? ` -d ${shellQuote(option.description)}` : '';
    const line = `complete -c ${programName} ${flags.join(' ')}${description}`;
    if (!optionLines.includes(line)) optionLines.push(line);
  }
  return [...lines, ...optionLines, ''].join('\n');
}

function findOption(program: Command, flag: string): Option | undefined {
  const search = (command: Command): Option | undefined => {
    for (const option of command.options) {
      if (option.long === flag || option.short === flag) return option;
    }
    for (const child of command.commands) {
      const found = search(child);
      if (found !== undefined) return found;
    }
    return undefined;
  };
  return search(program);
}

export function completionScript(program: Command, programName: string, shell: string): string {
  switch (shell) {
    case 'bash':
      return bashScript(program, programName);
    case 'zsh':
      return zshScript(program, programName);
    case 'fish':
      return fishScript(program, programName);
    default:
      throw new Error(`Unsupported shell: ${shell}. Use bash, zsh, or fish.`);
  }
}
